<?php

namespace Fundeuis\EducacionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CiudadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CiudadRepository extends EntityRepository {

    /**
     * Recibe el id del departamento
     * Recibe el nombre de la ciudad
     * 
     * @param type $departamento
     * @param type $ciudad
     */
    public function busquedaCiudad($departamento, $ciudad) {
        return $this->getEntityManager()
                        ->createQuery(
                                "SELECT c FROM FundeuisEducacionBundle:Ciudad c WHERE c.departamento = :departamento AND c.nombre LIKE :ciudad"
                        )
                        ->setParameter('departamento', $departamento)
                        ->setParameter('ciudad', '%' . $ciudad . '%')
                        ->getResult();
    }

}
