<?php

namespace Fundeuis\EducacionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EstudiantenfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstudiantenfRepository extends EntityRepository {

    public function busquedaFiltros($identificacion, $nombres, $apellidos) {
        return $this->getEntityManager()
                        ->createQuery(
                                "SELECT e FROM FundeuisEducacionBundle:Estudiantenf e WHERE e.documentoidentidad = :identificacion OR"
                                . "(e.nombres LIKE :nombres) OR"
                                . " (e.apellidos LIKE :apellidos)"
                        )
                        ->setParameter('nombres', '%' . $nombres . '%')
                        ->setParameter('apellidos', '%' . $apellidos . '%')
                        ->setParameter('identificacion', $identificacion)
                        ->getResult();
    }

}
