<?php

namespace Fundeuis\EducacionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioCursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioCursoRepository extends EntityRepository {

    /**
     * Buscar cursos del año actual y años anterior.
     * @return type
     */
    public function buscarCursosAno() {
        $year = \date('Y');
        $ayear = $year - 1;
        $aayear = $year - 2;
        return $this->getEntityManager()
                        ->createQuery('SELECT c FROM FundeuisEducacionBundle:Curso c WHERE c.fechainicio LIKE :fecha OR c.fechainicio LIKE :afecha OR c.fechainicio LIKE :aafecha ORDER BY c.fechainicio DESC')
                        ->setParameter('fecha', '%' . $year . '%')
                        ->setParameter('afecha', '%' . $ayear . '%')
                        ->setParameter('aafecha', '%' . $aayear . '%')
                        ->getResult();
    }

    /**
     * Buscar cursos del año actual vigente. 
     * @return type
     */
    public function buscarCursosAnoActualVigente() {
        //$year = \date('Y');        
        return $this->getEntityManager()
                        ->createQuery('SELECT c FROM FundeuisEducacionBundle:Curso c WHERE'
                                . ' c.fechainicio BETWEEN :fecha AND c.fechafin ORDER BY c.fechainicio ASC')
                        ->setParameter('fecha', new \DateTime("now"))
                        ->getResult();
    }

    /**
     * Comprueba que el curso a matricular este vigente. 
     * Recibe el id del curso
     * @return type
     */
    public function comprobarCursosAnoActualVigente($idCurso) {
        //$year = \date('Y');        
        return $this->getEntityManager()
                        ->createQuery('SELECT c FROM FundeuisEducacionBundle:Curso c WHERE '
                                . 'c.fechainicio BETWEEN :fecha AND c.fechafin AND '
                                . 'c.idcurso = :id '
                                . 'ORDER BY c.fechainicio ASC')
                        ->setParameter('fecha', new \DateTime("now"))
                        ->setParameter('id', $idCurso)
                        ->getResult();
    }

    /**
     * Buscar matricula en curso.
     * @return type
     */
    public function buscarMatriculaUsuarioActiva1($estudiantenf) {
        // $fecha = \date('y/m/d');
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT uc FROM FundeuisEducacionBundle:UsuarioCurso uc JOIN FundeuisEducacionBundle:Curso c
                                WITH uc.estudiantenf = :estudiantenf 
                                AND uc.curso = c.idcurso 
                                AND (:fecha BETWEEN c.fechainicio AND c.fechafin)'
                        )
                        ->setParameter('estudiantenf', $estudiantenf)
                        ->setParameter('fecha', new \DateTime("now"))
                        ->getResult();
    }

    /**
     * Buscar matricula en curso.
     * @return type
     */
    public function buscarMatriculaUsuarioActiva2($estudiantenf) {
        // $fecha = \date('y/m/d');
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT uc FROM FundeuisEducacionBundle:UsuarioCurso uc JOIN FundeuisEducacionBundle:Curso c
                                WITH uc.estudiantenf = :estudiantenf 
                                AND uc.curso = c.idcurso 
                                AND (c.fechainicio BETWEEN :fecha AND c.fechafin)'
                        )
                        ->setParameter('estudiantenf', $estudiantenf)
                        ->setParameter('fecha', new \DateTime("now"))
                        ->getResult();
    }

}
